#!/bin/bash

# Make sure we are in the script directory
ScriptDIR=$(cd `dirname $0` && pwd)
if [ $ScriptDIR != $PWD ]; then
   echo "Ce script doit être executé depuis son dossier" 1>&2
   exit
fi

#On récupère le nombre de sessions actives de Yane
C=`sudo ./yane  -l | wc -l`

#On vérifie qu'aucune session n'est déjà lancée
if [ "$C" != "0" ] ; then
  echo "Une session est déjà lancée pour la fermer executez la commande:"
  echo "   STOP"
  exit

else
  #On copie les scripts dans le dossier partagé du Docker correspondant
  cp ./scripts/box_1 ./files/box_1/etc/scripts/init
  cp ./scripts/box_2 ./files/box_2/etc/scripts/init
  cp ./scripts/serveur_web_user ./files/serveur_web_user/var/scripts/init
  cp ./scripts/Routeur_FAI ./files/Routeur_FAI/etc/scripts/init
  cp ./scripts/Routeur_1 ./files/Routeur_1/etc/scripts/init
  cp ./scripts/Routeur_2 ./files/Routeur_2/etc/scripts/init
  cp ./scripts/Routeur_services ./files/Routeur_services/etc/scripts/init
  cp ./scripts/Routeur_services_reseau ./files/Routeur_services_reseau/etc/scripts/init
  cp ./scripts/serveur_web ./files/serveur_web/var/scripts/init
  cp ./scripts/serveur_dns ./files/serveur_dns/etc/scripts/init
  echo 'Chargement des VM..'
  #On lance Yane
  sudo ./yane > /dev/null
  exit
fi
